server:
  port: 8082

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: payment-service
  datasource:
    url: jdbc:h2:mem:payments
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  h2:
    console:
      enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: payment-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.projetofinal.paymentservice.event
        spring.json.value.default.type: com.projetofinal.paymentservice.event.OrderCreatedEvent
        spring.json.use.type.headers: false

app:
  kafka:
    topic:
      pedidos: pedidos-criados

gateway:
  stripe:
    secret-key: ${STRIPE_SECRET_KEY:sk_test_placeholder}
